# Generated by Django 5.1.2 on 2024-10-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('summary', models.TextField()),
                ('misinformation_category', models.CharField(choices=[('major_misinformation', 'Major Misinformation'), ('minor_inaccuracies', 'Minor Inaccuracies'), ('recommended', 'Recommended Article')], max_length=50)),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
